services:
  backend-test:
    container_name: backend-test
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - ENVIRONMENT=test
    ports:
      - "5000:5000"
    env_file:
      - ./.env.test
    depends_on:
      - database-test
    networks:
      - test-network

  database-test:
    image: postgres:16
    container_name: database-test
    env_file:
      - ./.env.test
    ports:
      - "5434:5432"
    volumes:
      - postgres_database_test:/var/lib/postgresql/data/
    networks:
      - test-network

networks:
  test-network:

volumes:
  postgres_database_test:
