services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/backend
    depends_on:
      - database
    env_file:
      - ./.env
    networks:
      - production

  database:
    image: postgres:16
    container_name: database_new
    env_file:
      - ./.env
    ports:
      - "5433:5432"
    volumes:
      - postgres_database:/var/lib/postgresql/data/
    networks:
      - production


networks:
  production:


volumes:
  postgres_database: