name: Run Tests
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          docker-compose -f docker-compose.test.yml up --build -d

      - name: Run Tests
        run: |
          docker-compose exec backend-test pytest -v
